/**
 * Seed script — run with:
 *   cd apps/api && npx ts-node -r tsconfig-paths/register src/seed/seed.ts
 */
import 'reflect-metadata';
import * as dotenv from 'dotenv';
dotenv.config();

import { DataSource } from 'typeorm';
import { Benchmark } from '../entities/benchmark.entity';
import { Client } from '../entities/client.entity';
import { Product } from '../entities/product.entity';
import { MediaPlan } from '../entities/media-plan.entity';
import { MediaPlanRow } from '../entities/media-plan-row.entity';
import { Audience } from '../entities/audience.entity';
import { CreativeType } from '../entities/creative-type.entity';

const ds = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST ?? 'localhost',
  port: Number(process.env.DB_PORT ?? 5432),
  database: process.env.DB_NAME ?? 'planflow',
  username: process.env.DB_USER ?? 'planflow',
  password: process.env.DB_PASS ?? 'planflow_dev',
  entities: [
    Benchmark,
    Client,
    Product,
    MediaPlan,
    MediaPlanRow,
    Audience,
    CreativeType,
  ],
  synchronize: true,
});

// ─── Benchmark data extracted from JM___Media_KPI_Forcast_.xlsx ──────────────

type BenchmarkSeed = Omit<Benchmark, 'id' | 'updatedAt'>;

const n = (v: string | null | undefined): number | null => {
  if (!v || v.trim() === '' || v === 'N/A' || v === 'TBD' || v === 'Depends')
    return null;
  const num = parseFloat(v.replace(/[^0-9.]/g, ''));
  return isNaN(num) ? null : num;
};

// Helper: parse "35 - 65" or "0.001 - 0.1" style strings → [low, high]
// Also handles "150 <" as [null, 150]
const parseRange = (
  val: string | null | undefined,
): [number | null, number | null] => {
  if (
    !val ||
    val.trim() === '' ||
    ['N/A', 'TBD', 'Depends', 'Can be vary'].includes(val.trim())
  )
    return [null, null];
  const lt = val.match(/^([0-9.]+)\s*</);
  if (lt) return [null, parseFloat(lt[1])];
  const dash = val.match(/([0-9.]+)\s*[-–]\s*([0-9.]+)/);
  if (dash) return [parseFloat(dash[1]), parseFloat(dash[2])];
  const single = parseFloat(val.replace(/[^0-9.]/g, ''));
  return isNaN(single) ? [null, null] : [single, single];
};

// Structured seed rows
const benchmarks: BenchmarkSeed[] = [
  // ══════════════════════════════════════════════════════════════
  // LOCAL-MASS — AWARENESS
  // ══════════════════════════════════════════════════════════════
  {
    audienceType: 'mass',
    objective: 'awareness',
    platform: 'meta_ig',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: 35,
    cpmHigh: 65,
    cprLow: 37,
    cprHigh: 75,
    cpeLow: 3,
    cpeHigh: 8,
    cpcLow: null,
    cpcHigh: 150,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Can be vary',
  },
  {
    audienceType: 'mass',
    objective: 'awareness',
    platform: 'meta',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: 35,
    cpmHigh: 65,
    cprLow: 37,
    cprHigh: 75,
    cpeLow: 3,
    cpeHigh: 8,
    cpcLow: null,
    cpcHigh: 150,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Can be vary',
  },
  {
    audienceType: 'mass',
    objective: 'awareness',
    platform: 'ig',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: 40,
    cpmHigh: 70,
    cprLow: 40,
    cprHigh: 75,
    cpeLow: 6,
    cpeHigh: 14,
    cpcLow: null,
    cpcHigh: 300,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Can be vary',
  },
  {
    audienceType: 'mass',
    objective: 'awareness',
    platform: 'gdn',
    minDuration: '3 weeks or above',
    minDailyBudget: 'USD 10 Min',
    currency: 'USD',
    cpmLow: 0.06,
    cpmHigh: 0.1,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 0.06,
    cpcHigh: 0.1,
    ctrLow: 0.01,
    ctrHigh: 1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Can be vary',
  },
  {
    audienceType: 'mass',
    objective: 'awareness',
    platform: 'youtube_video',
    minDuration: '3 weeks or above',
    minDailyBudget: 'USD 10 Min',
    currency: 'USD',
    cpmLow: 0.1,
    cpmHigh: 2,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 0.06,
    cpcHigh: 0.1,
    ctrLow: 0.01,
    ctrHigh: 1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Can be vary',
  },
  {
    audienceType: 'mass',
    objective: 'awareness',
    platform: 'youtube_bumper',
    minDuration: '3 weeks or above',
    minDailyBudget: 'USD 10 Min',
    currency: 'USD',
    cpmLow: 1.5,
    cpmHigh: 2,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 0.06,
    cpcHigh: 0.1,
    ctrLow: 0.01,
    ctrHigh: 1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Can be vary',
  },
  // ══════════════════════════════════════════════════════════════
  // LOCAL-MASS — ENGAGEMENT
  // ══════════════════════════════════════════════════════════════
  {
    audienceType: 'mass',
    objective: 'engagement',
    platform: 'meta_ig',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: 110,
    cpmHigh: 160,
    cprLow: 150,
    cprHigh: 200,
    cpeLow: 1,
    cpeHigh: 4,
    cpcLow: 60,
    cpcHigh: 150,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: 0.15,
    cpv2sHigh: 0.2,
    cpvTvLow: 0.9,
    cpvTvHigh: 2,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Can be vary',
  },
  {
    audienceType: 'mass',
    objective: 'engagement',
    platform: 'meta',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: 110,
    cpmHigh: 160,
    cprLow: 150,
    cprHigh: 200,
    cpeLow: 1,
    cpeHigh: 4,
    cpcLow: 60,
    cpcHigh: 150,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: 0.15,
    cpv2sHigh: 0.2,
    cpvTvLow: 0.9,
    cpvTvHigh: 2,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Can be vary',
  },
  {
    audienceType: 'mass',
    objective: 'engagement',
    platform: 'ig',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: 120,
    cpmHigh: 170,
    cprLow: 150,
    cprHigh: 250,
    cpeLow: 2,
    cpeHigh: 7,
    cpcLow: 100,
    cpcHigh: 150,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: 0.25,
    cpv2sHigh: 0.3,
    cpvTvLow: 1.8,
    cpvTvHigh: 3.5,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Can be vary',
  },
  {
    audienceType: 'mass',
    objective: 'engagement',
    platform: 'ig_follower',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: 180,
    cpmHigh: 225,
    cprLow: 300,
    cprHigh: 500,
    cpeLow: 7,
    cpeHigh: 11,
    cpcLow: null,
    cpcHigh: null,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: 28,
    pageLikeHigh: 50,
    frequency: 'Can be vary',
  },
  {
    audienceType: 'mass',
    objective: 'engagement',
    platform: 'meta_page_like',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: 150,
    cpmHigh: 200,
    cprLow: 170,
    cprHigh: 200,
    cpeLow: 4,
    cpeHigh: 8,
    cpcLow: 50,
    cpcHigh: 80,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: 15,
    pageLikeHigh: 30,
    frequency: 'Can be vary',
  },
  // ══════════════════════════════════════════════════════════════
  // LOCAL-MASS — TRAFFIC
  // ══════════════════════════════════════════════════════════════
  {
    audienceType: 'mass',
    objective: 'traffic',
    platform: 'meta_ig',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: 55,
    cpmHigh: 90,
    cprLow: 62,
    cprHigh: 90,
    cpeLow: 3,
    cpeHigh: 8,
    cpcLow: 3,
    cpcHigh: 6,
    ctrLow: 0.07,
    ctrHigh: 2,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: 20,
    cplvHigh: 100,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'mass',
    objective: 'traffic',
    platform: 'meta',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: 55,
    cpmHigh: 90,
    cprLow: 62,
    cprHigh: 90,
    cpeLow: 3,
    cpeHigh: 8,
    cpcLow: 3,
    cpcHigh: 6,
    ctrLow: 0.07,
    ctrHigh: 2,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: 20,
    cplvHigh: 100,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'mass',
    objective: 'traffic',
    platform: 'ig',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: 55,
    cpmHigh: 90,
    cprLow: 70,
    cprHigh: 160,
    cpeLow: 5,
    cpeHigh: 9,
    cpcLow: 6,
    cpcHigh: 12,
    ctrLow: null,
    ctrHigh: null,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'mass',
    objective: 'traffic',
    platform: 'gdn',
    minDuration: '3 weeks or above',
    minDailyBudget: 'USD 10 Min',
    currency: 'USD',
    cpmLow: 1,
    cpmHigh: 2.3,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 0.02,
    cpcHigh: 0.1,
    ctrLow: 0.0116,
    ctrHigh: 0.095,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'mass',
    objective: 'traffic',
    platform: 'search',
    minDuration: '3 weeks or above',
    minDailyBudget: 'USD 10 Min',
    currency: 'USD',
    cpmLow: 0.88,
    cpmHigh: 1.2,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 0.03,
    cpcHigh: 0.2,
    ctrLow: 0.013,
    ctrHigh: 0.0444,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'mass',
    objective: 'traffic',
    platform: 'demand_gen',
    minDuration: '3 weeks or above',
    minDailyBudget: 'USD 10 Min',
    currency: 'USD',
    cpmLow: 1.7,
    cpmHigh: 3,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 0.3,
    cpcHigh: 1,
    ctrLow: null,
    ctrHigh: null,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  // ══════════════════════════════════════════════════════════════
  // LOCAL-MASS — LEADS
  // ══════════════════════════════════════════════════════════════
  {
    audienceType: 'mass',
    objective: 'leads',
    platform: 'meta_ig',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: null,
    cpmHigh: null,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: null,
    cpcHigh: null,
    ctrLow: null,
    ctrHigh: null,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: 35,
    cplHigh: 75,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'mass',
    objective: 'leads',
    platform: 'meta',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: null,
    cpmHigh: null,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: null,
    cpcHigh: null,
    ctrLow: null,
    ctrHigh: null,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: 35,
    cplHigh: 75,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'mass',
    objective: 'leads',
    platform: 'ig',
    minDuration: '3 weeks or above',
    minDailyBudget: 'LKR 1K Min',
    currency: 'LKR',
    cpmLow: null,
    cpmHigh: null,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: null,
    cpcHigh: null,
    ctrLow: null,
    ctrHigh: null,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: 57,
    cplHigh: 90,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'mass',
    objective: 'leads',
    platform: 'search',
    minDuration: '3 weeks or above',
    minDailyBudget: 'USD 10 Min',
    currency: 'USD',
    cpmLow: 9,
    cpmHigh: 15,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 0.05,
    cpcHigh: 0.1,
    ctrLow: null,
    ctrHigh: null,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: 7,
    cplHigh: 12,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  // ══════════════════════════════════════════════════════════════
  // LOCAL-NICHE — AWARENESS
  // ══════════════════════════════════════════════════════════════
  {
    audienceType: 'niche',
    objective: 'awareness',
    platform: 'meta_ig',
    minDuration: 'Below 2 weeks',
    minDailyBudget: 'LKR 1K <',
    currency: 'LKR',
    cpmLow: 65,
    cpmHigh: 85,
    cprLow: 75,
    cprHigh: 90,
    cpeLow: 3,
    cpeHigh: 8,
    cpcLow: null,
    cpcHigh: 200,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Depends',
  },
  {
    audienceType: 'niche',
    objective: 'awareness',
    platform: 'meta',
    minDuration: 'Below 2 weeks',
    minDailyBudget: 'LKR 1K <',
    currency: 'LKR',
    cpmLow: 65,
    cpmHigh: 85,
    cprLow: 75,
    cprHigh: 90,
    cpeLow: 3,
    cpeHigh: 8,
    cpcLow: null,
    cpcHigh: 200,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Depends',
  },
  {
    audienceType: 'niche',
    objective: 'awareness',
    platform: 'ig',
    minDuration: 'Below 2 weeks',
    minDailyBudget: 'LKR 1K <',
    currency: 'LKR',
    cpmLow: 70,
    cpmHigh: 90,
    cprLow: 83,
    cprHigh: 100,
    cpeLow: 6,
    cpeHigh: 9,
    cpcLow: null,
    cpcHigh: 200,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Depends',
  },
  {
    audienceType: 'niche',
    objective: 'awareness',
    platform: 'gdn',
    minDuration: 'Below 2 weeks',
    minDailyBudget: null,
    currency: 'USD',
    cpmLow: 0.06,
    cpmHigh: 0.1,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 0.06,
    cpcHigh: 0.1,
    ctrLow: 0.01,
    ctrHigh: 0.9,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Depends',
  },
  {
    audienceType: 'niche',
    objective: 'awareness',
    platform: 'youtube_video',
    minDuration: 'Below 2 weeks',
    minDailyBudget: null,
    currency: 'USD',
    cpmLow: 0.001,
    cpmHigh: 0.003,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 0.06,
    cpcHigh: 0.1,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Depends',
  },
  {
    audienceType: 'niche',
    objective: 'awareness',
    platform: 'youtube_bumper',
    minDuration: 'Below 2 weeks',
    minDailyBudget: null,
    currency: 'USD',
    cpmLow: 2,
    cpmHigh: 3,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 0.06,
    cpcHigh: 0.1,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: 'Depends',
  },
  // ══════════════════════════════════════════════════════════════
  // LOCAL-NICHE — ENGAGEMENT
  // ══════════════════════════════════════════════════════════════
  {
    audienceType: 'niche',
    objective: 'engagement',
    platform: 'meta_ig',
    minDuration: 'Below 2 weeks',
    minDailyBudget: 'LKR 1K <',
    currency: 'LKR',
    cpmLow: 119,
    cpmHigh: 230,
    cprLow: 130,
    cprHigh: 230,
    cpeLow: 3,
    cpeHigh: 7,
    cpcLow: 78,
    cpcHigh: 90,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: 0.3,
    cpv2sHigh: 1,
    cpvTvLow: 1,
    cpvTvHigh: 2.5,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'niche',
    objective: 'engagement',
    platform: 'meta',
    minDuration: 'Below 2 weeks',
    minDailyBudget: 'LKR 1K <',
    currency: 'LKR',
    cpmLow: 119,
    cpmHigh: 230,
    cprLow: 130,
    cprHigh: 230,
    cpeLow: 3,
    cpeHigh: 7,
    cpcLow: 78,
    cpcHigh: 90,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: 0.3,
    cpv2sHigh: 1,
    cpvTvLow: 1,
    cpvTvHigh: 2.5,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'niche',
    objective: 'engagement',
    platform: 'ig',
    minDuration: 'Below 2 weeks',
    minDailyBudget: 'LKR 1K <',
    currency: 'LKR',
    cpmLow: 125,
    cpmHigh: 230,
    cprLow: 150,
    cprHigh: 250,
    cpeLow: 4,
    cpeHigh: 8,
    cpcLow: null,
    cpcHigh: 200,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: 0.5,
    cpv2sHigh: 1.2,
    cpvTvLow: 1.3,
    cpvTvHigh: 2.8,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'niche',
    objective: 'engagement',
    platform: 'ig_follower',
    minDuration: 'Below 2 weeks',
    minDailyBudget: 'LKR 1K <',
    currency: 'LKR',
    cpmLow: 125,
    cpmHigh: 200,
    cprLow: 120,
    cprHigh: 200,
    cpeLow: 6,
    cpeHigh: 7,
    cpcLow: null,
    cpcHigh: 200,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: 40,
    pageLikeHigh: 70,
    frequency: null,
  },
  {
    audienceType: 'niche',
    objective: 'engagement',
    platform: 'meta_page_like',
    minDuration: 'Below 2 weeks',
    minDailyBudget: 'LKR 1K <',
    currency: 'LKR',
    cpmLow: 90,
    cpmHigh: 138,
    cprLow: 105,
    cprHigh: 130,
    cpeLow: 5,
    cpeHigh: 7,
    cpcLow: null,
    cpcHigh: 200,
    ctrLow: 0.001,
    ctrHigh: 0.1,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: 40,
    pageLikeHigh: 65,
    frequency: null,
  },
  // ══════════════════════════════════════════════════════════════
  // LOCAL-NICHE — TRAFFIC
  // ══════════════════════════════════════════════════════════════
  {
    audienceType: 'niche',
    objective: 'traffic',
    platform: 'meta_ig',
    minDuration: 'Below 2 weeks',
    minDailyBudget: 'LKR 1K <',
    currency: 'LKR',
    cpmLow: 55,
    cpmHigh: 90,
    cprLow: 62,
    cprHigh: 90,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 6,
    cpcHigh: 8,
    ctrLow: 0.07,
    ctrHigh: 2,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: 20,
    cplvHigh: 100,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'niche',
    objective: 'traffic',
    platform: 'meta',
    minDuration: 'Below 2 weeks',
    minDailyBudget: 'LKR 1K <',
    currency: 'LKR',
    cpmLow: 55,
    cpmHigh: 90,
    cprLow: 62,
    cprHigh: 90,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 6,
    cpcHigh: 8,
    ctrLow: 0.07,
    ctrHigh: 2,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: 20,
    cplvHigh: 100,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'niche',
    objective: 'traffic',
    platform: 'ig',
    minDuration: 'Below 2 weeks',
    minDailyBudget: 'LKR 1K <',
    currency: 'LKR',
    cpmLow: null,
    cpmHigh: null,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 9,
    cpcHigh: 15,
    ctrLow: 0.07,
    ctrHigh: 3,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'niche',
    objective: 'traffic',
    platform: 'gdn',
    minDuration: 'Below 2 weeks',
    minDailyBudget: null,
    currency: 'USD',
    cpmLow: 0.48,
    cpmHigh: 1.9,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 0.06,
    cpcHigh: 1,
    ctrLow: null,
    ctrHigh: null,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'niche',
    objective: 'traffic',
    platform: 'search',
    minDuration: 'Below 2 weeks',
    minDailyBudget: null,
    currency: 'USD',
    cpmLow: 0.001,
    cpmHigh: 0.003,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 0.5,
    cpcHigh: 1,
    ctrLow: null,
    ctrHigh: null,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: null,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  // ══════════════════════════════════════════════════════════════
  // LOCAL-NICHE — LEADS
  // ══════════════════════════════════════════════════════════════
  {
    audienceType: 'niche',
    objective: 'leads',
    platform: 'meta_ig',
    minDuration: 'Below 2 weeks',
    minDailyBudget: 'LKR 1K <',
    currency: 'LKR',
    cpmLow: null,
    cpmHigh: null,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: null,
    cpcHigh: null,
    ctrLow: null,
    ctrHigh: null,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: 35,
    cplHigh: null,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'niche',
    objective: 'leads',
    platform: 'search',
    minDuration: 'Below 2 weeks',
    minDailyBudget: null,
    currency: 'USD',
    cpmLow: 9,
    cpmHigh: 15,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 3,
    cpcHigh: 9,
    ctrLow: null,
    ctrHigh: null,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: 20,
    cplHigh: 40,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
  {
    audienceType: 'niche',
    objective: 'leads',
    platform: 'demand_gen',
    minDuration: 'Below 2 weeks',
    minDailyBudget: null,
    currency: 'USD',
    cpmLow: 1.7,
    cpmHigh: 3,
    cprLow: null,
    cprHigh: null,
    cpeLow: null,
    cpeHigh: null,
    cpcLow: 0.3,
    cpcHigh: 1,
    ctrLow: null,
    ctrHigh: null,
    cpv2sLow: null,
    cpv2sHigh: null,
    cpvTvLow: null,
    cpvTvHigh: null,
    cplvLow: null,
    cplvHigh: null,
    cplLow: 35,
    cplHigh: 50,
    pageLikeLow: null,
    pageLikeHigh: null,
    frequency: null,
  },
];

// ─── Client + Product seed data ──────────────────────────────────────────────

interface ClientSeed {
  name: string;
  products: string[];
  defaultFee1Pct: number;
  defaultFee1Label: string;
  defaultFee2Pct: number | null;
  defaultFee2Label: string | null;
  defaultCurrency: string;
}

const clientsData: ClientSeed[] = [
  {
    name: "People's Bank",
    products: [
      'Credit Cards',
      'Leasing',
      'Remittance',
      'FX-FUTURE',
      'Christmas Campaign',
      'SME',
    ],
    defaultFee1Pct: 15,
    defaultFee1Label: 'Management Fee',
    defaultFee2Pct: null,
    defaultFee2Label: null,
    defaultCurrency: 'LKR',
  },
  {
    name: 'Fonterra',
    products: [
      'Anchor PediaPro',
      'Anchor Hot Chocolate',
      'Anchor Milk',
      'Anchor Newdale',
    ],
    defaultFee1Pct: 12,
    defaultFee1Label: 'Management Fee',
    defaultFee2Pct: 6.25,
    defaultFee2Label: 'ASP Fee',
    defaultCurrency: 'LKR',
  },
  {
    name: 'Ritzbury',
    products: ['Deckers', 'Choco Bar'],
    defaultFee1Pct: 15,
    defaultFee1Label: 'Management Fee',
    defaultFee2Pct: null,
    defaultFee2Label: null,
    defaultCurrency: 'LKR',
  },
];

// ─── Main ─────────────────────────────────────────────────────────────────────

async function seed() {
  await ds.initialize();
  console.log('DB connected');

  const benchmarkRepo = ds.getRepository(Benchmark);
  const clientRepo = ds.getRepository(Client);
  const productRepo = ds.getRepository(Product);

  // Clear existing data
  await ds.query(
    'TRUNCATE TABLE media_plan_rows, media_plans, products, clients, benchmarks, audiences, creative_types RESTART IDENTITY CASCADE',
  );

  // Seed benchmarks
  await benchmarkRepo.save(benchmarks.map((b) => benchmarkRepo.create(b)));
  console.log(`Seeded ${benchmarks.length} benchmarks`);

  // Seed clients + products
  for (const cd of clientsData) {
    const client = await clientRepo.save(
      clientRepo.create({
        name: cd.name,
        defaultFee1Pct: cd.defaultFee1Pct,
        defaultFee1Label: cd.defaultFee1Label,
        defaultFee2Pct: cd.defaultFee2Pct,
        defaultFee2Label: cd.defaultFee2Label,
        defaultCurrency: cd.defaultCurrency,
      }),
    );
    const products = cd.products.map((name) =>
      productRepo.create({ name, clientId: client.id }),
    );
    await productRepo.save(products);
    console.log(`Seeded client: ${cd.name} with ${products.length} products`);
  }

  // Seed audiences
  const audienceRepo = ds.getRepository(Audience);
  const audienceCount = await audienceRepo.count();
  if (audienceCount === 0) {
    await audienceRepo.save([
      {
        name: 'Overseas audience',
        audienceType: 'niche',
        location: 'Middle East, Korea',
        estimatedSizeMin: '1.2M',
        estimatedSizeMax: '1.4M',
        behaviors: 'Lived in Sri Lanka',
        clientId: null,
      },
      {
        name: 'Local audience',
        audienceType: 'mass',
        location: 'Sri Lanka',
        estimatedSizeMin: '4.8M',
        estimatedSizeMax: '5.4M',
        behaviors: 'Family of those abroad',
        clientId: null,
      },
      {
        name: 'SMEs',
        audienceType: 'niche',
        location: 'Sri Lanka',
        estimatedSizeMin: '750K',
        estimatedSizeMax: '850K',
        interests: 'Small business owner',
        clientId: null,
      },
      {
        name: 'Tamil Audience',
        audienceType: 'niche',
        location: 'Sri Lanka',
        clientId: null,
      },
      {
        name: 'Advantage+ Audience',
        audienceType: 'mass',
        demographics: 'Broad targeting',
        estimatedSizeMin: null,
        estimatedSizeMax: null,
        clientId: null,
      },
      {
        name: 'Mass Youth 18-34',
        audienceType: 'mass',
        location: 'Sri Lanka',
        ageMin: 18,
        ageMax: 34,
        estimatedSizeMin: '3M',
        estimatedSizeMax: '4M',
        clientId: null,
      },
      {
        name: 'Parents with preschoolers',
        audienceType: 'niche',
        location: 'Sri Lanka',
        demographics: 'Parents, children 0-5',
        clientId: null,
      },
      {
        name: 'Engaged Shoppers',
        audienceType: 'mass',
        location: 'Sri Lanka',
        behaviors: 'Engaged shoppers',
        clientId: null,
      },
    ]);
    console.log('Seeded 8 audiences');
  }

  // Seed creative types
  const creativeTypeRepo = ds.getRepository(CreativeType);
  const ctCount = await creativeTypeRepo.count();
  if (ctCount === 0) {
    await creativeTypeRepo.save([
      { name: 'Static Post', category: 'static' },
      { name: 'Carousel', category: 'static' },
      { name: 'Main Video', category: 'video' },
      { name: 'Video Cuts', category: 'video' },
      { name: 'Bumper Ad', category: 'video' },
      { name: 'Vertical Content', category: 'video' },
      { name: 'Highlight Reel', category: 'video' },
      { name: 'GIF', category: 'animated' },
      { name: 'Display Banner', category: 'display' },
      { name: 'Animated Banner', category: 'animated' },
    ]);
    console.log('Seeded 10 creative types');
  }

  await ds.destroy();
  console.log('Done!');
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
